### ISSUE TITLE
checkpoint warning

### ISSUE THREAD

**Issue by Bian-666** [HYUNJS/SGT#10]
![image](https://user-images.githubusercontent.com/77476607/218031280-d92e2ee9-5450-40a0-9077-5a28faefa850.png)

I meet this warning when i training the MOT17. what's this?

**Comment by HYUNJS** [comment]
This indicates that the tracker is randomly initialized instead of loading the weights from the checkpoint. If you use CenterNet pretrained weight (COCO) to train the SGT, then you can ignore this warning since CenterNet only has the weight for detector.
