### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by samahkouni** [HYUNJS/SGT#4]
Hello ,Thank you for your great job. I'm interested in your work.
I want to know when code will be released.

**Comment by HYUNJS** [comment]
Thank you for your interest. Sorry for the late release. I will release the code this week.

**Comment by samahkouni** [comment]
hello, 
I want to know if the  code will be released sooner .

**Comment by HYUNJS** [comment]
Hi, I will release the code in few days after cleaning the code and writing guideline. If you are in a hurry, I can send you the code via email.

**Comment by samahkouni** [comment]
yes ,please  
my email: kouni.samah@gmail.com 
and thanks a lot

**Comment by HYUNJS** [comment]
I sent the code. Please check your email.

**Comment by HYUNJS** [comment]
The code is released. Please check the updated version.
