### ISSUE TITLE
What GPU are you using for training models？

### ISSUE THREAD

**Issue by Bian-666** [HYUNJS/SGT#5]

**Comment by HYUNJS** [comment]
* I have verified the code with P40, V100, rtx3090, and rtx2080ti.
* Please note that with rtx3090, you cannot use the released docker image of cuda 10.1 since only cuda 11+ is supported by rtx3090. For the details please refer to INSTALL.md

**Comment by Bian-666** [comment]
> * I have verified the code with P40, V100, rtx3090, and rtx2080ti.
> * Please note that with rtx3090, you cannot use the released docker image of cuda 10.1 since only cuda 11+ is supported by rtx3090. For the details please refer to INSTALL.md

Thank you for your prompt reply，and how many rtx3090 did you use? I only have a single 3090.

**Comment by HYUNJS** [comment]
A single rtx3090 may be insufficient to train with a batch size of 12. You can try with a smaller batch size (e.g., 8 or 10)
