### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mirramira** [HYUNJS/SGT#6]
hello ,
Thank you for your great job,
i have this error   when i run the command : 
**docker run --rm -it -d --shm-size=16G --gpus  all  -v E:/testSGT/:/var/lib/docke --name sgt -p 3000:22 -p 3001:8081 jshyunaa/sgt:cu113**
 error : 
**4047f072d415073b2d4e2b5951c39efa0e4a9152564ce005ca9b1659fe9f80a3
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as ‘legacy’
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown.**

I’m on a Windows 10 Professionnel Version 21H2 home computer, and I have a NVIDIA GeForce GT 710   gpu . This is the output when running docker --version : `Docker version 20.10.17, build 100c701, on both systems (WSL and windows).

**Comment by HYUNJS** [comment]
Hello, thank you for your interest.

The problem seems to be caused by WSL (maybe the version of WSL). I would recommend installing Linux individually, instead of WSL, since the system is also dependent on the Window version.

**Comment by mirramira** [comment]
hello , thank you to  reply my comments. 
i will  try installing linux , and about the gpu a have NVIDIA GeForce GT 710 gpu it is fine to work with.

**Comment by HYUNJS** [comment]
I don't think it is enough. NVIDIA GeForce GT 710 is only 1GB or 2GB which is too small to load a deep learning model.  For training SGT with batch size of 12, ~40GB is required.

**Comment by mirramira** [comment]
thank a lot for your help

**Comment by mirramira** [comment]
Hello HYUNJS,
sorry but can I ask you to help me more, i'm a student in masters from
Tunisia and I can't afford to buy a gpu rtx3090.
Can I send you a KTH  dataset  to test in your SGT?
Thanks in advance
