### ISSUE TITLE
no detectron2 file 

### ISSUE THREAD

**Issue by liuqigui** [HYUNJS/SGT#7]
i have a question! When python projects/SGT/train_net.py --config-file projects/SGT/configs/MOT17/sgt_dla34.yaml --data-dir /root/datasets --num-gpus 2 OUTPUT_DIR /root/sgt_output/mot17_val/dla34_mot17-CH, the computer shows Traceback (most recent call last):
  File "FairMOT-base/src/train_net.py", line 9, in <module>
    import detectron2.utils.comm as comm
ModuleNotFoundError: No module named 'detectron2'

where is the detectron2?  could you send me the detectron2 file?

**Comment by HYUNJS** [comment]
Please refer Dockerfile as in https://github.com/HYUNJS/SGT/blob/main/INSTALL.md
* You can download the certain version of detectron2 with following command
```
# for detectron2 v0.4.1
pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.4.1'
# for detectron2 v0.6
pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.6'
```
![image](https://user-images.githubusercontent.com/29353227/198894281-ce076431-4779-4f48-bfb9-455fc534cbd9.png)

**Comment by liuqigui** [comment]
yes! i do it! but i have a new question. How did you set up your dataset, especially what are mot17_sub.train and mot17_sub.val for mix_data_list?

**Comment by HYUNJS** [comment]
* Please follow the steps mentioned in https://github.com/HYUNJS/SGT/blob/main/DATASET.md
* Please remove comment (#) for Line 77-78 (https://github.com/HYUNJS/SGT/blob/main/projects/Datasets/MOT/gen_trainval.py#L77)

**Comment by liuqigui** [comment]
No, no, no, I think you misunderstood me, I mean what are mot17_sub.train and mot17_sub.val in the MIX dataset?

**Comment by HYUNJS** [comment]
MOT17 challenge does not provide validation dataset so I divide MOT17 training set into mot17_sub.train and mot17_sub.val. The first half frames of a video is used as the training set and the rest are the validation set. By the way, MIX dataset is just a different format between MOT dataset 

mot17_sub.train/val include the list of files used for train/val
