### ISSUE TITLE
no ctdet_coco_dla_2x_converted.pth file and the eval phase

### ISSUE THREAD

**Issue by mirramira** [HYUNJS/SGT#8]
hello,
i didin't  find the file **WEIGHTS: "/root/checkpoints/ctdet_coco_dla_2x_converted.pth"** for **/SGT/projects/SGT/configs/hieve/sgt_dla34.yaml** 
 in **[download model weights](https://hkustconnect-my.sharepoint.com/:f:/g/personal/jhyunaa_connect_ust_hk/ErLZ6DG6CndHs-Lo12AxZKAB1kb4AJCh8adtnRAlXTNuzA?e=rKeboA)**

**Comment by mirramira** [comment]
hello, i hope you are fine.
i was able to run the SGT on google colab pro+ with a v100 gpu and cuda 11.3 . i get the result from the train of MOT17 
as fallow :
![mot17train](https://user-images.githubusercontent.com/116167525/201205736-0d16f77c-feda-4177-8676-57fc42a6461b.png)
but in the eval phase i get this : 
![mot17eval](https://user-images.githubusercontent.com/116167525/201205932-64354948-33e9-47d4-87ed-db9b57a0b9fc.png)
plz, i need help to undrestand  what's wrong. 
thanks

**Comment by HYUNJS** [comment]
> i didin't find the file WEIGHTS: "/root/checkpoints/ctdet_coco_dla_2x_converted.pth" for /SGT/projects/SGT/configs/hieve/sgt_dla34.yaml
* You can use centernet_dla34_coco.pth

> i was able to run the SGT on google colab pro+ with a v100 gpu and cuda 11.3 . i get the result from the train of MOT17 but in the eval phase i get this :
* Do you mean that you can get the result when you run the command for training the model, but cannot get the result by running the command for eval?
* Did you change the model weight path in the config file when you run evaluation mode?

**Comment by mirramira** [comment]
yes i can't get the result for the eval , i have change the path  in this file **-config-file /content/SGT/projects/SGT/configs/MOT17/sgt_dla34.yaml** i get all the file in the output empty

**Comment by HYUNJS** [comment]
* What model weight did you use for evaluation?
* Can you show me the entire log when you run?

**Comment by mirramira** [comment]
i send you the google colab file the last cell is the eval code

**Comment by mirramira** [comment]
i send you mail with the code

**Comment by HYUNJS** [comment]
* It seems that you still use the COCO pretrained CenterNet checkpoint to run evaluation. If you are experimenting using Colab, the update of a file may take seconds sometimes. Instead of modifying the code, you could simply add one more argument
```MODEL.WEIGHTS /path/to/the/weight/file.pth``` at the end. Note that it should be located after all arguments with "--xx yy".
![image](https://user-images.githubusercontent.com/29353227/201489699-b488a703-5d43-46ff-9912-72ba3cdb2340.png)

**Comment by mirramira** [comment]
which  weight i use  to run the  evaluation.

**Comment by HYUNJS** [comment]
* According to your log file, you used "/content/.../centernet_dla34_coco.pth"
* You should comment out the line for the path of the model weight of SGT. You can choose one of the checkpoints I provided or the one you trained.

**Comment by mirramira** [comment]
thank you a lot for your great effort in helping me
